INSERT INTO localized_string (id, en, de) VALUES ('mission.tutorial', 'Tutorial Mission', 'Tutorialmission')
INSERT INTO localized_string (id, en, de) VALUES ('mission.superimportantmission', 'Super Important Mission', 'Superwichtige Mission')
INSERT INTO localized_string (id, en, de) VALUES ('skill.A', 'A', 'A')
INSERT INTO localized_string (id, en, de) VALUES ('skill.B', 'B', 'B')
INSERT INTO localized_string (id, en, de) VALUES ('skill.C', 'C', 'C')
INSERT INTO localized_string (id, en, de) VALUES ('skill.D', 'D', 'D')
INSERT INTO localized_string (id, en, de) VALUES ('skill.E', 'E', 'E')
INSERT INTO localized_string (id, en, de) VALUES ('skill.F', 'F', 'F')
INSERT INTO localized_string (id, en, de) VALUES ('skill.G', 'G', 'G')
INSERT INTO localized_string (id, en, de) VALUES ('skill.H', 'H', 'H')
INSERT INTO localized_string (id, en, de) VALUES ('character.tutorial', 'Tutorial Character', 'Tutorialcharakter')
INSERT INTO localized_string (id, en, de) VALUES ('character.awesomenewcharacter', 'Awesome New Character', 'Toller neuer Character')
