INSERT INTO localized_string (id, en, de) VALUES ('mission.tutorial', 'Tutorial Mission', 'Tutorialmission')
INSERT INTO localized_string (id, en, de) VALUES ('mission.superimportantmission', 'Medical Assistance', 'Medizinische Hilfe')
INSERT INTO localized_string (id, en, de) VALUES ('skill.A', 'Medical', 'Arzt')
INSERT INTO localized_string (id, en, de) VALUES ('skill.B', 'Biology', 'Biologie')
INSERT INTO localized_string (id, en, de) VALUES ('skill.C', 'C', 'C')
INSERT INTO localized_string (id, en, de) VALUES ('skill.D', 'D', 'D')
INSERT INTO localized_string (id, en, de) VALUES ('skill.E', 'E', 'E')
INSERT INTO localized_string (id, en, de) VALUES ('skill.F', 'F', 'F')
INSERT INTO localized_string (id, en, de) VALUES ('skill.G', 'G', 'G')
INSERT INTO localized_string (id, en, de) VALUES ('skill.H', 'H', 'H')
INSERT INTO localized_string (id, en, de) VALUES ('character.tutorial', 'Dr. Alexandra Lake', 'Dr. Alexandra Lake')
INSERT INTO localized_string (id, en, de) VALUES ('character.awesomenewcharacter', 'Skye Kearney', 'Skye Kearney')
INSERT INTO localized_string (id, en, de) VALUES ('menu.account', 'Account', 'Account')
INSERT INTO localized_string (id, en, de) VALUES ('menu.missions', 'Missions', 'Missionen')
